# -*- coding: utf-8 -*-
"""worlddata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktO2s-BoCN0HtI2xajs5gfg2kk9LdxNM
"""

import numpy as np
import pandas as pd

def ols_reg(filename):
    global df
    df = pd.read_csv(f"{filename}.csv")     #assumption: the directory of both files is same  
    print(df.head())

ols_reg('world data')

"""The dataset extracted from the world data shows 15 unique countries over the period of 10 years with GDP and social rating impact of the countries. """

df.head()

df.columns

df['Country'] =df['Country '].str.strip()

df.describe()

df['Country'].nunique()

df['Country'].unique()

df['Year'].nunique()

df['Year'].unique()

df.columns

df['GDP'].value_counts()

df['ratingimpact'].value_counts()

df.corr()

"""There are high correlation of years recorded over the impact ratings in the dataset. This shows that the occurence in the countires over the years has a huge effort on the social impact ratings in the countries. """